package com.techknowns.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "expense")
public class Expense {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String expenseId;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private String category;

    @DynamoDBAttribute
    private double amount;

    @DynamoDBAttribute
    private String date;
}
